require:
- rubocop-performance
- rubocop-rails
- rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - '!ruby/regexp/old_and_unused\.rb$/'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'app/helpers/*'
    - 'spec/rails_helper.rb'
  TargetRubyVersion: 2.7.2

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case

Style/GuardClause:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false  

RSpec/DescribedClass:
  Enabled: false